### ISSUE TITLE
Remove/deprecate the old spotify client

### ISSUE THREAD

**Issue by vansante** [svenwiltink/go-MusicBot#15]
The unauthorized spotify API is being deprecated :(:

https://github.com/zmb3/spotify/issues/41

**Comment by SvenWiltink** [comment]
:cry:

**Comment by SvenWiltink** [comment]
The latest version of zmb3/spotify actually breaks our code and is preventing me from packaging the musicbot. 

@vansante Will you do the honors of removing the defaultclient from this repo?

relevant commit: https://github.com/zmb3/spotify/commit/55f605253770ee45b33ff9f9af53589393fddfa2
sad buildlog: https://launchpadlibrarian.net/325949134/buildlog_ubuntu-zesty-amd64.golang-github-svenwiltink-go-musicbot_1.5.0+git20170628.4.09dc300-1ubuntu3_BUILDING.txt.gz

**Comment by vansante** [comment]
This is done
